### ISSUE TITLE
Multiple account/wallet support

### ISSUE THREAD

**Issue by gasull** [asgardex/asgardex-desktop#109]
## Description

It seems multiple wallet support was dropped recently.  I used to be able to add several wallets, but now I can only add or create one wallet to a new installation.  Previously added or created wallets remain.

I found tickets related to this from the old repo, that I had to dig very hard:

- [Handling multiple wallets](https://archive.is/sgQ2x)
- [(EPIC) Multi-wallet support](https://archive.is/AZO3S)
- [UI: Multi-account](https://archive.is/LqraO)

These above are links to archive.today caches of Yandex caches of the deleted issues from the old repo.  That's how hard I had to dig this information.

**Comment by Thorian1te** [comment]
it was never dropped, and is still there and working nominally 
<img width="747" alt="image" src="https://github.com/asgardex/asgardex-desktop/assets/100335276/82f95326-a3b7-4eb3-a0a3-b9b8d2b2dcf4">

**Comment by gasull** [comment]
I see.  So I need to unlock a wallet before I can add another wallet.

Why?

This is a UX problem.  It isn't obvious at all.

**Comment by Thorian1te** [comment]
It seems this is the case. I cannot speak for the dev that wrote the code in any version before v1.20.0 
Well it's more of a problem to the user if they can't unlock a wallet before adding another.
