### ISSUE TITLE
I need to download a new wallet i forgot how to do it have you got any videos ,my old wallet i delete could not get it to work 

### ISSUE THREAD

**Issue by roboning** [asgardex/asgardex-desktop#111]
## Your Environment

- ASGARDEX desktop version:

- Operating system and version:

- Transaction hash(es):

- Wallet address(es):

**Comment by Thorian1te** [comment]
Steps 

1. Open asgardex go to settings hit unlock wallet
2. Left corner hit Forget Wallet. 
3. Create a new keystore.
