### ISSUE TITLE
Add Bitcoin Legacy Wallet Support

### ISSUE THREAD

**Issue by Dakey86** [asgardex/asgardex-desktop#112]
## Description

When adding Ledger wallet, only Segwit type are for now supported, is it possible to add legacy wallet too?

**Comment by GrassRootsCrypto** [comment]
This is possible. It will require a custom derivation path to be selected in the wallet settings.

For implementation, I think this could be done by changing the `rootDerivationPaths` within `UtxoClientParams` when creating btcClient, but I assume we could only show one at a time. 
This is also a trap as if it is not set correctly. funds can appear to go missing.

**Comment by GrassRootsCrypto** [comment]
@Dakey86 it is going to be too complex to add this and it is not needed. 
If you have bitcoin in a 1 or 3 address, send it to a bc1 address and it is supported.
