### ISSUE TITLE
USDT to RUNE swap does not work

### ISSUE THREAD

**Issue by wegg3** [asgardex/asgardex-desktop#125]
## Your Environment

- ASGARDEX desktop version:

- Operating system and version:

- Transaction hash(es):

- Wallet address(es):

**Comment by wegg3** [comment]
ASGARDEX desktop V1.21.0
macOS Sonoma 14.2.1
I have balances of RUNE + ETH + USDT

MIT ] (ERROR={"REASON":"CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT","CODE":"UNPREDICTABLE_GAS_LIMIT","ERROR":{"REASON":"PROCESSING RESPONSE ERROR","CODE":"SERVER_ERROR","BODY":"{\"JSONRPC\":\"2.0\",\"ID\":1,\"ERROR\":{\"CODE\":-32000,\"MESSAGE\":\"EXECUTION REVERTED\"}}\N","ERROR"::

**Comment by wegg3** [comment]
I can swap RUNE to USDT no problem

**Comment by wegg3** [comment]
https://runescan.io/tx/461D81DD5C52E9597447ED662D85B80647265D864A5B4BAB50B70E00DE931DBC

**Comment by GrassRootsCrypto** [comment]
@wegg3 I assume it is working now?
