### ISSUE TITLE
ETH BALANCE - NO PROVIDER ABLE TO GET BALANCE (API RATE LIMIT EXCEEDED)

### ISSUE THREAD

**Issue by lumogate** [asgardex/asgardex-desktop#129]
I built asgardex from source. Everything seemed fined until i imported wallet. All Balance are fine except for ETH

403 API RATE LIMIT EXCEEDED. Within Wallet it says NO PROVIDER ABLE TO GET BALANCE

i created an account on ethplorer.io to get API KEY then i tried creating a .env file and buiding from source hoping it solves it but it does not seem to have any effect

What am i doing wrong?

.env file i created 

# ASGARDEX
# Enabling specific chains only - no value set means all available chains will be enabled in ASGDX
REACT_APP_CHAINS_ENABLED=THOR,BNB,BTC,LTC,BCH,ETH,DOGE,GAIA

# Enable specific network(s) only - no value set means stagnet + mainnet will be enabled by default
REACT_APP_NETWORKS=testnet,stagenet,mainnet

# Set default network - needs to be part of REACT_APP_NETWORKS
REACT_APP_DEFAULT_NETWORK=mainnet

# ETH
REACT_APP_ETHPLORER_API_KEY=ApiKeyFromEthPlorer
REACT_APP_ETHPLORER_API_URL=https://api.ethplorer.io

- ASGARDEX desktop version:
1.21.0
- Operating system and version:
Mac OS Ventura 13.5.1

**Comment by Thorian1te** [comment]
don't use EthPlorer use etherscan

**Comment by lumogate** [comment]
Yes thank you figured it out. Forgot to close this
