### ISSUE TITLE
REMOVE: Asgardex-midgard replace with xchain-midgard

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#13]
## Description

There are two dependencies referencing the same api package 
Since package thorchain query already depends on xchain-midgard switch to using this one instead of the other
Remove the generated files for Midgard as well

## TODO

- Remove '@thorchain/asgardex-midgard'
- Replace with 'xchainjs/xchain-midgard'

**Comment by GrassRootsCrypto** [comment]
Done, no longer in package.json
