### ISSUE TITLE
Custom BIP84 Paths for Bitcoin and other compatible assets

### ISSUE THREAD

**Issue by szamani20** [asgardex/asgardex-desktop#130]
## Background

Hardware wallets like Ledger offer various derivation path construction by leveraging building blocks of `BIP84` standard, e.g. `account` and `address_index` as explained here:
[https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki)

## Current Behavior
ASGARDEX allows users to set `address_index` of `BIP84` derivation path struction in its UI as depicted below:

![ASGARDEX BIP84 address_index](https://github.com/asgardex/asgardex-desktop/assets/12181220/9c03605d-4044-4438-a5be-dfa88146e397)

## Proposed Behavior
It would certainly benefit users to allow them to also set the `account` value, as explained in `BIP84`, as well. Perhaps in the form of a second entry box right next to INDEX in the picture above. Or even better, an advanced option to allow users to enter their own derivation path (this might need some regex validation).

![ASGARDEX BIP84 address_index and account](https://github.com/asgardex/asgardex-desktop/assets/12181220/f91d2433-a73c-45e8-935d-bdaee686071b)

## Possible Starting Point
Upon looking at the code, I found that the [address.ts](https://github.com/asgardex/asgardex-desktop/blob/develop/src/main/api/ledger/bitcoin/address.ts) file could be altered to add support for an `account` variable alongside the existing `walletIndex` variable. Just throwing ideas around.

**Comment by Thorian1te** [comment]
thank you will look into it 👍
