### ISSUE TITLE
usdt to wbtc or eth error

### ISSUE THREAD

**Issue by bitdaric** [asgardex/asgardex-desktop#133]
swaping 20000 usdt to wbtc or eth get this error:

CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT [ SEE: HTTPS://LINKS.ETHERS.ORG/V5-ERRORS-UNPREDICTABLE_GAS_LIMIT ] (ERROR={"REASON":"CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT","CODE":"UNPREDICTABLE_GAS_LIMIT"

**Comment by GrassRootsCrypto** [comment]
Thanks @bitdaric for reporting. I am assuming you are using the latest version. 

Can you confirm you have enough gas for the transaction and if you have approved the USDT contract before?

**Comment by bitdaric** [comment]
usdt approval button appeared just one time, I changed page and after return not displayed again for me, I just saw swap button (maybe approved I don't remember!)
 and yes I have 0.1 eth

**Comment by GrassRootsCrypto** [comment]
Thanks, I think it is an approve error and it is fixed in the next release.
