### ISSUE TITLE
'Ledgererror 27904: Instruction not supported' upon Rune-side Ledger LP deposit

### ISSUE THREAD

**Issue by fedorovian** [asgardex/asgardex-desktop#134]
## Description

When symmetrically adding funds to an LP and using a Ledger wallet for both Rune and the native asset (BCH), the BCH transaction is successful, however, I receive the following error when it comes time to push the unsigned Rune transaction to my Ledger:

> DEPOSIT LEDGER THOR TX FAILED. (LEDGERERROR 27904: INSTRUCTION NOT SUPPORTED)

## Steps to Reproduce

1. Select Manage LP. Under the Add tab, select the radio boxes for Ledger for both the Rune side and the asset side. (BCH in this case.)
2. Choose amounts and press Add.
3. As expected, ASGARDEX prompts to open the BCH app on the Ledger, and successfully pushes the unsigned BCH TX to the Ledger.
4. Sign and broadcast the BCH transaction.
5. At this point, I expect to be prompted to open the Rune app on my Ledger to complete the Rune deposit. However, unexpectedly I receive the above `LEDGERERROR 27904`, before being prompted or having the opportunity to switch apps on my Ledger.

## Workaround

I eventually see a notice in ASGARDEX for 'pending assets found', informing me of a recovery process on ThorSwap. On ThorSwap, I've been able to withdraw the BCH, or complete the Rune side deposit using my Ledger Rune wallet.

## Environment

- ASGARDEX: v1.21.0
- Ledger THORchain app: v2.2.0 
- Ledger firmware: v1.1.0
- OS: Ubuntu 23.10

![rune-side](https://github.com/asgardex/asgardex-desktop/assets/102703725/901103fc-ff01-41b3-a43f-41f9d6088025)

**Comment by fedorovian** [comment]
Replicated this on ASGARDEX v1.21.1 and Ledger firmware v1.1.1.

When running the .AppImage, no new logs are output in the terminal when this occurs.

**Comment by GrassRootsCrypto** [comment]
@fedorovian 
The logic has been updated in 1.21.5. 
1. Please ensure the ledger thorchain app is the latest. (V2.2.0).
2. Retest when 1.21.5 is released.
