### ISSUE TITLE
Maya Dex Integration

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#136]
Integrate with Maya Dex to allow swaps.

Savers are not supported, they are displayed only.

**Comment by hilawe** [comment]
Hi @GrassRootsCrypto @Thorian1te, do you know when you'll add the ability to view/deposit/withdraw funds from a pool for the Maya Network (e.g. for an asset like Dash)? Is there a backlog task for this that I missed?
