### ISSUE TITLE
pressing refresh not giving new rate

### ISSUE THREAD

**Issue by bitdaric** [asgardex/asgardex-desktop#139]
in swap page, when an amount is set, pressing refresh not giving new output rate.
for example at btc = 40000 usdt rate if we set 10000 usdt, it is now 0.025 btc in output
now btc = 41000 usdt, we press refresh. the output should be 0.02439 btc but it remain 0.025 btc

**Comment by GrassRootsCrypto** [comment]
@bitdaric the refresh updates your balance, like it does on the wallet screen. 

The quote updates every time you change the input amount. There is no need to refresh the quote.
