### ISSUE TITLE
tell user swap rate is fixed or float

### ISSUE THREAD

**Issue by bitdaric** [asgardex/asgardex-desktop#140]
sometimes we get different amount from a swap. you should state it below swap button that it is a floating rate or fixed rate.

**Comment by Thorian1te** [comment]
are you using streaming for swaps ?

**Comment by bitdaric** [comment]
I use default settings

**Comment by GrassRootsCrypto** [comment]
@bitdaric this is how AMMs work. Only CEXs using instant spot or order books can give you exact amounts.
