### ISSUE TITLE
Erroneous Swap Memo Creation When ":LIM" Parameter is Missing

### ISSUE THREAD

**Issue by ghasemkiani** [asgardex/asgardex-desktop#142]
In the Send form, when a swap memo is detected, affiliate parameters are automatically appended to the memo. However, since the ":LIM" parameter is optional in the swap memo (SWAP:ASSET:DESTADDR:LIM/INTERVAL/QUANTITY:AFFILIATE:FEE) it may not be provided. Simply adding ':dx:5' to the memo creates an erroneous memo and the swap will not be performed.

## Prerequisites
This occurs when a swap memo lacks the optional ":LIM" parameter and the affiliate parts.

## Expected Behavior

The memo should include an (empty or zero) limit parameter in this situation.
## Current Behavior

An erroneous memo is created in which the affiliate id will be interpreted as the limit value, and since it cannot be converted to a number, the swap will not be performed.
## Steps to Reproduce

Use the Send form with a swap memo without the limit parameter, e.g. "=:s:0x000..."

## Possible Solution

In the file SendFormEVM.tsx (and other respective send form files), the line `memoValue += ':dx:5'` can be replaced with something like this:
```ts
memoValue += memoValue.split(':').length < 4 ? '::dx:5' : ':dx:5';
```
I think this may solve the problem, though I have not tested.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: V1.21.0

- Operating system and version: Windows 10

## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by Thorian1te** [comment]
are you able to show a screen shot of what the memo looks like ? 
and what you think it should look like
for example this is a memo with out a limit 
`=:THOR.RUNE:THOR1RR6RAHHD4SY76A7RDXKJAEN2Q4K4PW2G06W7QP::DX:5`

for example this is a memo with a limit 
`=:THOR.RUNE:THOR1RR6RAHHD4SY76A7RDXKJAEN2Q4K4PW2G06W7QP:21342345:DX:5`

for example this is a memo with a stream (preferred memo for swaps) 
`=:THOR.RUNE:THOR1RR6RAHHD4SY76A7RDXKJAEN2Q4K4PW2G06W7QP:0/1/0:DX:5`

**Comment by ghasemkiani** [comment]
This is an example memo that will cause the problem: `=:THOR.RUNE:THOR1RR6RAHHD4SY76A7RDXKJAEN2Q4K4PW2G06W7QP`. As far as I know, this is a valid memo, because both the limit parameter and the two affiliate parts are optional. The program appends `:dx:5` to this, without considering the fact that the limit part is also missing.

**Comment by GrassRootsCrypto** [comment]
@ghasemkiani please provide an erroneous memo that asgardex creates. 

In Swap, if instant is selected, user can select slippage tolerance which sets the LIM, else there is no LIM if SS is selected as it is not required.
In Send, if there user wants to add a custom swap memo affiliate is added. It is up to the user to get the memo correct as they are writing it manually.

**Comment by Thorian1te** [comment]
fixed thank you for pointing that out
