### ISSUE TITLE
ADD: Better TX Page View/Copy

### ISSUE THREAD

**Issue by thorchain-admin** [asgardex/asgardex-desktop#15]
# SEND L1
Show the default explorer option (etherscan, mempool etc)

# SWAP, SAVE, LEND
Show it on https://thorchain.net/tx/692df1242442ab852cbafe56b87531aa150239782e0a2eaa5c57f221fd6af333

This captures much better info than explorers

# Copy Button
Make it copy only the txhash, not the full URL link

**Comment by GrassRootsCrypto** [comment]
Looks good, all three parts are there after a transaction. 
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/e93c56c9-ea59-4fa4-8c2b-e7b9ffe560a0)
