### ISSUE TITLE
Please add ability to complete an LP add

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#153]
## Description

Just today I had an LP add operation (initiated from Asgardex) that got hung up. One of the smart people on the THORChain Telegram figured out that the asset side of the LP add was successful but the RUNE side failed for some reason.

Asgardex gave no indication that I could find that the LP add was stuck. I was however able to load the keystore wallet in THORSwap and that said the LP add was incomplete and gave me a "complete" button to press and then verify to go ahead.

Something like this would be a great addition to Asgardex.

**Comment by GrassRootsCrypto** [comment]
Yes, Asgardex does detect if one side is missing but doesn't help you fix it. I have the same issue on my ledger and wish there was a simple way to fix it or be told "send x asset to this address with the memo abc."

It shouldn't be too hard to work out what is required to fix it up and show the user.

**Comment by erikd** [comment]
Awesome, thanks. Look forward to the next release.

**Comment by erikd** [comment]
Just needed to use this and it was trivially easy to fix and incomplete LP add. Thanks again!
