### ISSUE TITLE
restore wallet

### ISSUE THREAD

**Issue by bitdaric** [asgardex/asgardex-desktop#161]
Can not find where I can enter seed to restore a wallet in new version? where is import/export buttons?

**Comment by bitdaric** [comment]
ok I find that I should unlock a wallet to import another one but this is not correct way. I forgot wallet password and I couldn't unlock it so I have to create a wallet and unlock it to be able to import another wallet I want!

**Comment by GrassRootsCrypto** [comment]
> ok I find that I should unlock a wallet to import another one but this is not correct way. I forgot wallet password and I couldn't unlock it so I have to create a wallet and unlock it to be able to import another wallet I want!

Glad you managed to get it working. 
Yes that is the current functionality, but will see if it can be improved.

**Comment by Thorian1te** [comment]
This has been fixed already, you can create a wallet if you forget the password 'not ideal, store password in password manager'
