### ISSUE TITLE
'Pending assets found' mistakenly suggests both assets should be RUNE

### ISSUE THREAD

**Issue by fedorovian** [asgardex/asgardex-desktop#174]
## Description

If pending assets are found, ASGARDEX mistakenly believes the missing LP deposit is RUNE, despite showing the correct amount for what should be, in this case, BCH.

## Background

I used ThorSwap to place an LP deposit using my Ledger wallet for both RUNE & BCH. (I've successfully used ThorSwap to do so previously, as I'm currently unable on ASGARDEX due to https://github.com/asgardex/asgardex-desktop/issues/134). However, while the RUNE-side deposit on ThorSwap was successful, the BCH side was not, giving a generic 'Add liquidity failed' message.

When switching to ASGARDEX, I was prompted by a 'Pending assets found' message to complete the deposit under Wallet > LP Shares > BCH > Manage LP.

However, instead of correctly listing the missing asset as BCH, it instead lists it as RUNE, alongside the originally completed RUNE deposit. (See screenshot.) The amount for the missing asset is correct, despite the asset name/icon being incorrect.

Pressing 'Complete LP' pulls up a dialogue box, which prompts to send the (correct) amount of (incorrect) RUNE. Additionally, the memo listed is that of the 'Thor TX memo', whereas I believe this ought to be the 'Asset TX memo'.

## Environment

- ASGARDEX: v1.21.4
- OS: Ubuntu 23.10

![complete-lp-1](https://github.com/asgardex/asgardex-desktop/assets/102703725/00aa4cd9-c472-4e1b-a401-bfb4ecd09d41)

![complete-lp-2](https://github.com/asgardex/asgardex-desktop/assets/102703725/53515693-ab27-4dd4-92f5-fc31ff7244d4)

**Comment by GrassRootsCrypto** [comment]
Done and tested bot ways (RUNE and Asset)
