### ISSUE TITLE
Add: More actions to asset details page 

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#178]
## Description

Most of the actions in the drop down box of the main wallet page should also be in the asset details page.

**Comment by GrassRootsCrypto** [comment]
Adding Swap and where appropriate, Manage LP and Deposit when the asset page is loaded. 

Feedback:
Cacao Asset - needs deposit
Cacao and RUNE assets, can't manage LP
Maya - can't swap or manage lp
Can't swap source to target, e.g. BTC to BTC. (AssetDetails.tsx)

**Comment by GrassRootsCrypto** [comment]
Done - but noting that earn is missing.
