### ISSUE TITLE
Asgardex Desktop Not Working

### ISSUE THREAD

**Issue by Jlynde74** [asgardex/asgardex-desktop#180]
I downloaded Asgardex Desktop probably about 3 years ago and moved my Rune to it. I have not been in it since. When I open it now, it looks like it wants to load properly and then the screen turn white. I have tried updating to a new version but that isn’t working either.

**Comment by GrassRootsCrypto** [comment]
@Jlynde74 did you update the Bep2 RUNE to Native RUNE?

**Comment by GrassRootsCrypto** [comment]
No response so closing.
