### ISSUE TITLE
Issue with Desktop Asgardex

### ISSUE THREAD

**Issue by martyree** [asgardex/asgardex-desktop#182]
## Issue description

When I open Asgardex I get an error message  Ajaxerror: ajaxerror
Then when I go to my wallet, my Bitcoin, Thorchain, and Litecoin all have errors.
No amount of refreshing solves the errors.
I'm tempted to remove the wallet and restore with the newest version, but don't know what that would accomplish.
<img width="1339" alt="Ajaxerror" src="https://github.com/asgardex/asgardex-desktop/assets/85951109/b819ab35-0b6d-40f2-a3a6-dca0fe381b48">
<img width="1339" alt="wallet error" src="https://github.com/asgardex/asgardex-desktop/assets/85951109/ff7225a7-6cbf-4fec-a7ba-4d305bae31c5">

## Your Environment

- ASGARDEX desktop version:
I think it is v0.3.1 that's what it says under Client Midguard Version
I don't know where else to look.
- Operating system and version:
 running Windows 11 Home 
version 22H2
- Transaction hash(es): I don't know what this is.
 
- Wallet address(es):

**Comment by GrassRootsCrypto** [comment]
@martyree it would appear you are using an old version. 
Please download the latest version from https://www.asgardex.com/installer or https://github.com/asgardex/asgardex-desktop/releases/tag/v1.21.4

**Comment by martyree** [comment]
Could you please tell me if I'm supposed to remove my old wallet before I install a new one, or will it install over the old one?
Do I remove, install, and restore?  Or just install over the old one?  How exactly?
Thank you.

**Comment by GrassRootsCrypto** [comment]
> Could you please tell me if I'm supposed to remove my old wallet before I install a new one, or will it install over the old one? Do I remove, install, and restore? Or just install over the old one? How exactly? Thank you.

I would try and install over the top first. If that doesn't work, remove and re-install. 
Ensure you have a backup of your seed words before you do so.
