### ISSUE TITLE
Remove the limit of 1 BTC (and any other limits for other token/coin) for viewing the preview of the quotes

### ISSUE THREAD

**Issue by HostFat** [asgardex/asgardex-desktop#186]
I see that here it isn't possible to put an higher number then 1 BTC to ask for the quotes of value of the possible swaps.
Maybe there are other limits for other coin/token, I think that all them can be removed.
![image](https://github.com/asgardex/asgardex-desktop/assets/644416/b98dbd76-3f36-4eae-8666-8afd10131fab)

**Comment by HostFat** [comment]
It seems also that when there is a wallet open, it isn't possible to get quotas that are over the balances on the addresses, the user need to close the wallet to being able again to get the quotas.

**Comment by GrassRootsCrypto** [comment]
Has been increased to 500 BTC worth.
