### ISSUE TITLE
Error NO PROVIDER ABLE TO GET BALANCE

### ISSUE THREAD

**Issue by paju1986** [asgardex/asgardex-desktop#19]
I have the following error then i open my wallet.
On the Bitcoin, LiteCoin and Dodge addresses i get this error:

NO PROVIDER ABLE TO GET BALANCE

Also on the TOTAL BALANCE OF POOL ASSETS i get:
LOADING BALANCES FAILED. NO PROVIDER ABLE TO GET BALANCE (ERRORID: GET_BALANCES)

The other addresses seem to work fine.

Im using the relase version 1.20.2 on Arch Linux from the AppImage.

**Comment by Thorian1te** [comment]
The Api key reached its request limit. Just try again later

**Comment by GrassRootsCrypto** [comment]
Made error messages more user-friendly.
