### ISSUE TITLE
Ability to add new (existing) Keystore wallet

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#190]
## Description

I have a Keystore wallet created by another app (eg THORSwap) but I could not figure out a way to import it. Asgardex allows me to open an existing one, or create a new one.

I have gone the other way, openning an Asgardex Keystore wallet in THORSwap, when THORSwap had a feature that Asgardex was missing (probably LP add completion which Asgardex now has).

**Comment by GrassRootsCrypto** [comment]
Thanks for posting. 
Yes, if the wallet is locked, there is no way to import. 

If you create a new wallet, and then go to settings then create a wallet, you will get an import option.
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/80d448c9-3f98-4ae1-87d9-153c200bf4db)

Then you can upload the keystore file (just ignore the error)
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/c43cdd27-d6c3-47a7-9969-002a230394d8)


I agree, we should have the import option if the wallet is locked or there is no wallet.

**Comment by erikd** [comment]
Thanks. Will check that out and report back. Probably won't have time until at least tomorrow.
