### ISSUE TITLE
Bitcoin address reuse - Reload button not works

### ISSUE THREAD

**Issue by Taipanmgs** [asgardex/asgardex-desktop#191]
Using the same address for every Bitcoin transaction is not a good practice. It would be nice to be able to generate one for every transaction

## Expected Behavior

I would expect to be able to generate a new Bitcoin address whenever I want and perhaps paste a note/label for each transaction

## Current Behavior

Always shows the same Bitcoin address

## Steps to Reproduce

In Wallet go in Bitcoin. Always show same address.
If in wallet list I click "Reload" in anychain address I got same address

- ASGARDEX desktop version:
ASGARDEX-1.21.2-linux
- Operating system and version:
On Ubuntu 22.

**Comment by GrassRootsCrypto** [comment]
Fixed by https://github.com/asgardex/asgardex-desktop/issues/193

**Comment by GrassRootsCrypto** [comment]
Fixed by https://github.com/asgardex/asgardex-desktop/issues/130
Users have total control on BTC address with ledger.
