### ISSUE TITLE
Bond: Transaction Modal not removed. 

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#192]
Go to bond:

Send Bond Tx;

Transactional Modal is shown. 

When a transaction ID is sent back from 9R and a valid tx id response is received form thornode, the modal is not updated.
The user cannot copy the tx ID - the modal is stuck checking.  

![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/f28705af-1c6e-45b4-9ff2-2b4c50af0530)

**Comment by GrassRootsCrypto** [comment]
Will wait for the thorchain xchainjs package update. Needs #150

**Comment by GrassRootsCrypto** [comment]
Would be great if the error message was passed through. Some examples of errors sent back are:

1. Failed to execute message; message index: 0: cannot unbond while node is in active or ready status: unknown request
2. Failed to execute message; message index: 0: fail to unbond, still part of the retiring vault: 1 error occurred:

**Comment by GrassRootsCrypto** [comment]
Had an issue with Kuji and Cacao LP add where the modal hung. This is fixed with PR #252. The original issue remains this would be the case as I am trying to unbond from an active node. #233 should address this issue. 
Keeping open till the original issue is fixed.

**Comment by Thorian1te** [comment]
no closing this. non issue

**Comment by GrassRootsCrypto** [comment]
> no closing this. non issue

Is an issue as the UI fails to tell the user what is going on. If the tx fails then the user should be notified, not be given a modal that times out after 5 or so mins. The tx hash is valid and can be looked up on runescan. 
This may be fixed by other tickets but keeping open until it is.

**Comment by Thorian1te** [comment]
you can no longer unbond from an active mode. so closing
