### ISSUE TITLE
FIX: ASSET BSC.USDT does not show on balance

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#221]
## Description

Once xchainjs fixes the returned asset that matches a whitelisted asset update the package and test. 

## TODO

xchainjs returns BSC.BSC-USD-0x55d398326f99059ff775485246999027b3197955. 

Requires https://github.com/xchainjs/xchainjs-lib/issues/1153

**Comment by GrassRootsCrypto** [comment]
Temp fix applied in https://github.com/asgardex/asgardex-desktop/pull/250/files#diff-396cf241255f1a184acd0516cbad3a5afe2feed46e5ead1a4447171fcc64b44bR29

Will need a proper fix to come from xchainjs
