### ISSUE TITLE
FIX: Maya Liquidity page

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#224]
## Description

1. The liquidity Graph is not loaded for Maya Dex
Maya Dex, Pools, Available Pools, click on BTC Asset. The liquidity Graph is not loaded. (but loaded when THOR Dex is selected. 
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/ccbba912-9d05-45c9-bd09-0d528cafa859)

2. Errors are shown in Asset Liquidity section when changing Dex.
Maya Dex, Pools, Available Pools, click on RUNE Asset. Then change Dex. Errors are shown.
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/75f38218-900a-4c7d-9cea-fad433a80ba9)

3. Removed number 3

**Comment by Thorian1te** [comment]
thorchain ON Mayachain is halted. whats wrong with this 
<img width="888" alt="image" src="https://github.com/asgardex/asgardex-desktop/assets/100335276/cf6eb8de-0384-4180-9493-f241b38eaa45">

not a bug.
