### ISSUE TITLE
UPDATE: Build files to be updated to node 20 

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#229]
## Description

According to Github actions, node 12/16 is deprecated and should be upgraded to node20 
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by GrassRootsCrypto** [comment]
For GitHub actions only. 

Noting the readme states Electron v26.0.x` / Node `18.16.1`
