### ISSUE TITLE
FIX: ETH Send quoting wrong dollar value

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#230]
## Description

in the eth send window the dollar amount being quoted is incorrect. Check logic

**Comment by GrassRootsCrypto** [comment]
Amounts are incorrect when Dex = Maya only. 
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/44c79fbf-afcd-4227-82a9-e4a652cdafab)
Wallet Balance is $62 USD
