### ISSUE TITLE
CPU hogging on wallet page

### ISSUE THREAD

**Issue by eloyesp** [asgardex/asgardex-desktop#246]
There is a lot of CPU usage when the application is on the wallet page. It is already mentioned on #197 but it is marked as completed.

I've tested the version 1.21.6 and the issue is still present.

## Expected Behavior

My computer should not be burned by the app.

## Current Behavior

My computer had 90º in a couple of minutes.

## Steps to Reproduce

Just visit that page, but it seems like an environment specific issue.

## Possible Solution

As far as I could check, the problem seem to involve a process named `asgardex --type=renderer` many of them quite heavy on CPU usage.

## Your Environment - Release Version (skip if not using a release version)

I'm on a not so old Linux, in a recent computer but without video card (just the embedded one), the app version is  (appimage).

- ASGARDEX desktop version: 1.21.6
- Operating system and version: Trisquel 11 (Ubuntu based)

**Comment by Thorian1te** [comment]
ive done some performance improvements on the asset page. A new release will be out shortly if the problem still exist let us know.

**Comment by GrassRootsCrypto** [comment]
Tested on the branch and SO much better. There is no difference in CPU usage between the Asset and LP Shares tab.
