### ISSUE TITLE
1.21.7 Issues

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#255]
Several Issues Reported - tested and recorded with the latest release download. 

1. ATOM - sending Tx issue. Sending to another address via Keystore. The below error is displayed. 
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/36e663ea-4d9c-4b24-bbf2-965e8167b294)
Same occurs with other TXs, e.g. LP and Savers.

2. Maya LP Adding - no value shown. 
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/3fa236f3-9a4b-4da8-9972-45afbdf528de)

3. Maya LP Add. Asset Max button incorrectly increases the Maya Asset Side balance beyond the Cacao balance. 
Correct.
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/53813b19-cfa9-4dee-8795-6e7ec9c9ad25)
When pressing Asset Max
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/ab8ace62-5d13-439d-b43d-1cdaed27720a)

4. Hangs when trying to swap BSC.USDT to RUNE. Says asset balance is 0 when it is not so cannot swap.

**Comment by Thorian1te** [comment]
Atom is a non issue.
