### ISSUE TITLE
Maya: Natve TX fee should be 0.2

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#260]
## Description

The current Native TX fee is 0.05 when sending Maya assets, e.g. Cacao.
https://mayanode.mayachain.info/mayachain/mimir says 0.2.

## TODO

Change the Default Fee to 0.2 Cacao
Test with Send Cacao.

Requires https://github.com/xchainjs/xchainjs-lib/issues/1179

**Comment by Thorian1te** [comment]
fixed in 1.21.8
