### ISSUE TITLE
UPDATE: Bond Tools: Setting Node Operator Fee

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#280]
## Description

1) Pretty sure the fee is optional, should not be mandatory, its often easier to just add bond provider while leaving it unchanged because the op fee is global for all bp and not per bp 🙂

2) its not specified the fee is in what unit.. I know for 20% it should be 2000, but you add the 2 extra zero..  maybe at least specify that it should be specified in %.. 🙂

**Comment by GrassRootsCrypto** [comment]
1. Only a Node Operator can set a fee. Looking at THORNode, a fee doesn't need to be set. A field needs to be there and prob best to default it to whatever the node has "node_operator_fee" within the node endpoint. If the value is outside the range of 0 and 10000 (e.g -1), a fee is not set and the should set one. A user must enter a fee within that range. 

2. NODEOPERATORFEE is in basis points. Set as 5% and constants and 0% in mimir. Thornode docs (/openapi.yaml) suggest the default is 20% (2000 bps) is the default, but that is an example only. Only the NO sets the fee.
