### ISSUE TITLE
With "Filter values below $1", ETH.LINK is hidden even though its value is much more than $1.

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#283]
## Prerequisites

* Be in the RUNE/ETH.LINK pool
* Withdraw 100% of position
* Asgardex does not show the ETH.LINK after 3 hours

## Expected Behavior

Expect Asgardex to show ETH.LINK balance. thorchain.net explorer shows the withdrawal as successful. THORSwap wallet shows the expected balance.

Have tried the "refresh" button at the top of the "wallet" page as well as the "reload" button on ETH.
## Current Behavior

Asgardex does not show any ETH.LINK balance.

## Steps to Reproduce

1. Be in the RUNE/ETH.LINK pool
2. Withdraw
3. Asgardex does not show the ETH.LINK after 3 hours

## Your Environment - Release Version (skip if not using a release version)

Debian testing linux (fully up-to-date).

- ASGARDEX desktop version: Latest 1.21.8

- Operating system and version: Debian Testing (fully up-to-date).

**Comment by erikd** [comment]
If I unselect "FIlter all values below $1" it shows up.

So the bug is that it hides the value even though it shows the ETH.LINK balance as being worth very much more than US$1.

**Comment by GrassRootsCrypto** [comment]
This is a valid issue. 
Superseded by https://github.com/asgardex/asgardex-desktop/issues/287
Should be fixed in the next release.

**Comment by erikd** [comment]
Close in favor of #287.
