### ISSUE TITLE
ETH.LINK on the "assets" page has an "earn" (savers vault) button but there is no vault for this asset

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#284]
## Prerequisites

Have ETH.LINK

## Expected Behavior

There should not be an "earn" button for assets which do not have a savers vault.

## Current Behavior

ETH.LINK (and possibly others) have an "earn" link.

## Steps to Reproduce

1. Have ETH.LINK.
2. View the "assets" page.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 1.21.8

- Operating system and version: Debian testing

**Comment by GrassRootsCrypto** [comment]
Confirmed in 1.21.9 [develop](https://github.com/asgardex/asgardex-desktop/commit/bcffd2bc4427805852f6dde834b30b7b2280c3fd)

**Comment by Thorian1te** [comment]
interesting

**Comment by GrassRootsCrypto** [comment]
Fixed in PR #288
