### ISSUE TITLE
Wallet->Filter out empty balances filters out ERC20s with value

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#287]
## Expected Behavior

When Filter out empty balances filters is selected, all balances with $0 are removed. 
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/fe4b9e35-495c-4166-a984-e501ec95fad8)
This removed blank or assets with a value of $0

## Current Behavior

On the Ethereum chain, some ERC20s are filtered out when they have a value. Good Example is ETH.THOR and ETH.LINK

Before the filter is selected
![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/03f61066-a98d-472e-a39c-fee97bca22d2)

After the filter is selected

![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/4b895c61-54ba-4e5f-b5ec-11cd33eaf339)

## Steps to Reproduce

Get either ETH.LINK and use the filter

## Your Environment - Development Version (skip if not using a development version)
Latest on Develop Commit bcffd2bc4427805852f6dde834b30b7b2280c3fd

**Comment by erikd** [comment]
Possibly not just ERC20 tokens, but possibly also other tokens on other chains (like BEP20 on BSC etc).

**Comment by GrassRootsCrypto** [comment]
> Possibly not just ERC20 tokens, but possibly also other tokens on other chains (like BEP20 on BSC etc).

Thanks - tested with BSC also. Fixed in the linked PR, will be in the next release.
