### ISSUE TITLE
NO PROVIDER ABLE TO GET BALANCE

### ISSUE THREAD

**Issue by shawnpringle** [asgardex/asgardex-desktop#295]
Because the inability of the wallet to subtract from balances it sends, sometimes erroneous transactions are sent out.

## Prerequisites
Use ASGARD 1.21.9 and perhaps reproducible on any chain with an EVM.

## Expected Behavior
Expected behavior should show correct balance.

## Current Behavior
Shows "no provider able to get balance"

## Steps to Reproduce

1. Get some USDC on BSC.  
2. Spend some small amount of it.   
3. Now try to spend the rest. 
4. Now you cannot see your balance no matter how often you restart.
5. Unable to transfer

## Possible Solution
Allow the user to type in what he thinks the balance is, by checking out a block explorer.
Allow user to type in another provider URL for the chain.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version:  1.21.9

- Operating system and version: Linux 5.4.0-182-generic

## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by Thorian1te** [comment]
thanks for the bug report. we will look into it

**Comment by Thorian1te** [comment]
does the issue still exist?

**Comment by shawnpringle** [comment]
For myself on the newest ASGARD downloaded three weeks ago, the Bitcoin
Cash balance reads as zero.  I had to use another wallet to access my
funds.  It would have been a completely different level of bad if it were a
CEx.  Actually, I could say when it was a CEx but the thread here is not
for me to complain about them.  The point here is there is a work around.

**Comment by Thorian1te** [comment]
Okay need some more info, 
Asg version? 
obvious question, does the address hold a balance?
is it ledger or keystore? 
We have not seen any issues in testing.

**Comment by GrassRootsCrypto** [comment]
I have tested all sends and once the balance loads, the user's balance is displayed. 
There are updated keys for UTXO and EVM so the issue should no longer exist.

**Comment by shawnpringle** [comment]
The problem no longer is expressed.  Some bugs line up like eclipses and
they are just in software for years but we don't normally see them.
Fortunately this doesn't seem to be a serious one.  I wonder were  you ever
able to reproduce the issue?
