### ISSUE TITLE
Btc address retrieved from Ledger for account/index incorrect

### ISSUE THREAD

**Issue by pichacha** [asgardex/asgardex-desktop#296]
In version 1.21.9, attempting to add a BTC address from Ledger with an index number higher than 0 results in retrieving an incorrect address.

## Steps to Reproduce

If you use version 1.21.8 and retrieve a BTC address from Ledger with index of 1, the address will be correct. If you attempt to retrieve the address in version 1.21.9 with an Account number of 0 (Since that was being used by default in 1.21.8 even though multiple accounts was not available yet) and an index of 1, it will retrieve an address that is different than the one that was retrieved for Account 0, Index 1 for version 1.21.8.
To clarify, in 1.21.9, address retrieval for Account 0, Index 0 does result in the correct address that is same as the Account 0, Index 0 for 1.21.8. It is only with index numbers greater than 0 that the error occurs.

- ASGARDEX desktop version:
1.21.9
- Operating system and version:
Macbook Pro/Mac OS Ventura 13.4.1

**Comment by Thorian1te** [comment]
thank you for the bug report. we will look into this issue.
