### ISSUE TITLE
Can't send BTC with Asgardex wallet.........

### ISSUE THREAD

**Issue by Bardman98** [asgardex/asgardex-desktop#308]
## Issue description
Hi, Trying to move some of my BTC. I keep getting invalid address error code that cancels transaction. Mac OS up to date also had BNB/Rune LP shares deleted from my account. Rune scan show only .01 BNB withdrawn on 3/25/24 was worth at least 3 full BNB with matching Rune. Was pool deleted and I lost my assets? 
I am able to swap on platform just not able to send to cold wallet or Shapeshift. Please Advise. Thank you

## Your Environment

- ASGARDEX desktop version: 1.22.0

- Operating system and version:Mac OSI Sonoma 14.5

- Transaction hash(es):

- Wallet address(es):

**Comment by Thorian1te** [comment]
Bep BNB has been removed from Thorchain and sunsetted by finance. If you do not see any LP or assets it was because of this. Asgardex is just an interface with Thorchain & MayaProtocol. 
[BEP2 announcement](https://www.bnbchain.org/en/blog/bep2-bep8-asset-sunset-announcement)

>  invalid address error code that cancels transaction. It means that the btc address you are sending to is not compatible with our BTC chain client.

**Comment by Bardman98** [comment]
Hi again, Looks like I've suffered an irreversible loss, my bad, wow ! This fosters goodwill in the community? Who gets the benefit of my loss ? Was endeavoring to support the network. Seems I have !

**Comment by Thorian1te** [comment]
Again I repeat, Asgardex is just an interface. Your complaints have to be taken up with TC or Binance, from memory there was notices on all Thorchains social networks. All the interfaces including Asgardex had notices to, whether it was on discord or Twitter.

**Comment by Bardman98** [comment]
Thanks for your time. Get that it's an interface. was over my head in LP providing, missed the memos. Not blaming Asgardex Devs. Getting edified in DEX.   Live and learn have a happy day!
