### ISSUE TITLE
ETH/ERC20 tokens not being displayed

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#323]
## Prerequisites

A wallet with ERC20 tokens like ETH.GALA, ETH.AXS, and ETH.LRC.

## Expected Behavior

Display the balances of these tokens. It used to do this.

## Current Behavior

With 1.22.1, Asgradex only shows ETH, ETH.USDC and ETH.USDT, while etherscan.io does show the balances.

If I load the wallet in the THORSwap app, all the tokens are present,

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 1.22.1 installed from deb package.

- Operating system and version: Debian testing that is regularly updated.

**Comment by Thorian1te** [comment]
add them via wallet settings

**Comment by Thorian1te** [comment]
example below

![image](https://github.com/user-attachments/assets/2890083d-686d-4854-8884-b5fb86d83a0f)

**Comment by erikd** [comment]
Ok, that worked for ETH.LINK and ETH.SNX (both of which TC has pools for), but ETH.AXS, ETH.GALA and others are still not listed.

**Comment by Thorian1te** [comment]
and updated token list is in the next release 👍

**Comment by erikd** [comment]
Just FYI, I use Asgardex as a general multi-chain wallet, not just for TC related stuff.

**Comment by Thorian1te** [comment]
of course, your feed back is appreciated ❤️

**Comment by erikd** [comment]
@Thorian1te I just updated to `1.22.2` and I added these three tokens to the ETH display. After doing so `ETH.AXS` and `ETH.LRC` balances were correct, but the `ETH.GALA` balance was zero while the `GALA` balance on etherscan is non-zero.

**Comment by Thorian1te** [comment]
Arr the token contract that was created in the whitelist is the old one.. 
new one [GALA Etherscan] (https://etherscan.io/token/0xd1d2eb1b1e90b638588728b4130137d262c87cae)
  even in the latest [thornode latest](https://gitlab.com/thorchain/thornode/-/raw/develop/common/tokenlist/ethtokens/eth_mainnet_V128.json?ref_type=heads)
  its the old token contract.
  I might just give users the option to add their own contract regardless if its in the whitelist or not
``` {
    asset: {
      chain: ETHChain,
      symbol: "GALA-0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA",
      ticker: "GALA",
      synth: false,
    },
    iconUrl: O.some(
      "https://tokens.1inch.io/0x15d4c048f83bd7e37d49ea4c83a07267ec4203da.png"
    ),
  },```

**Comment by Thorian1te** [comment]
I've snuck in the updated gala contract in the latest release. :)
