### ISSUE TITLE
V1.22.2 - ERROR TRYING TO IMPORT LEDGER ACCOUNTS

### ISSUE THREAD

**Issue by glandsats** [asgardex/asgardex-desktop#340]
Ledger worked on previous version, updated to 1.22.2 and can't connect my ledger 

## Issue description
ERROR TRYING TO IMPORT LEDGER ACCOUNTS
INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/0: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/1: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/2: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/3: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/4: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/5: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER

![image](https://github.com/user-attachments/assets/8cb0b20d-2b79-405f-9610-b41176ab7c1f)

## Your Environment

- ASGARDEX desktop version: 1.22.2

- Operating system and version: Win11 24H2 and Ledger wallet

- Transaction hash(es):

- Wallet address(es):

**Comment by Clarevero1** [comment]
> Ledger worked on previous version, updated to 1.22.2 and can't connect my ledger
> 
> ## Issue description
> ERROR TRYING TO IMPORT LEDGER ACCOUNTS INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/0: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/1: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/2: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/3: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/4: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/5: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER
> 
> ![image](https://private-user-images.githubusercontent.com/33603809/363263979-8cb0b20d-2b79-405f-9610-b41176ab7c1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDMyNTMsIm5iZiI6MTcyNTA0Mjk1MywicGF0aCI6Ii8zMzYwMzgwOS8zNjMyNjM5NzktOGNiMGIyMGQtMmI3OS00MDVmLTk2MTAtYjQxMTc2YWI3YzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE4MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTFmMzNlMTUxZmY5NzM0MzA0OGZjZDk3OGRkZWVmNWUzYjhlMDMwNTAxNGVmZGZmNzE0NzMxMmJmZDc3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Lvfh73tKW5nF2wv076zGbGmqJeitE8aCzSGnj4dt6g)
> 
> ## Your Environment
> * ASGARDEX desktop version: 1.22.2
> 
> * Operating system and version: Win11 24H2 and Ledger wallet
> 
> * Transaction hash(es):
> 
> * Wallet address(es):

@glandsats You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by Thorian1te** [comment]
hope you didn't click that link. silly scammers

The error is a once off, we updated the json to include accounts. You can just re import the accounts again and it should work
