### ISSUE TITLE
Complete LP not working for on Maya

### ISSUE THREAD

**Issue by eloyesp** [asgardex/asgardex-desktop#356]
## background

I've tried to create an LP position on maya, it does two transactions, half on cacao (succeed) and the second one on the asset (in this case failed)...

## Current Behavior

When I go back to the add liquidity menu there is a warning message:

> Pending assets found (more information)

There is a lot of information, but part of that information is incorrect, the asset is not the one being deposited, it is RUNE (THOR).

Bellow, there is a green button to complete the LP, but it offer a RUNE transaction (with a memo that seems to be correct). the transaction obviously fail.

There is some data about the memo, the addresses and some text that mention a "custom deposit option in wallet", but I've found nothing about that...

## Expected Behavior

There should be a way to revert the cacao transaction and a way to complete the LP that works.

## Steps to Reproduce

I'm not sure how to reproduce the issue, because it needs a failed deposit transaction, I'm not even sure why it failed this time. May be the cacao part can be done manually to reproduce the bug:

1. Make a deposit transaction on the cacao side for an asset (Arbitrum), but do not make the deposit on the asset side.
2. Open Asgardex and try to add an LP on that same asset.

## Possible Solution

There should be a better error message, will the pending liquidity expire? knowing that would help a lot... Also, the "Complete LP" have no inputs, just a confirm/cancel button, may be givin more flexibility could help the user handle the situation better.

Also, I've found no way to revert the cacao transaction, so those cacao are trapped on the pending deposit and seems that there is no way to recover those.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 1.22.4  on Linux (AppImage)

**Comment by Thorian1te** [comment]
A fix for this is already on its way in the next release

**Comment by eloyesp** [comment]
Ok, seems to be fixed in #352
