### ISSUE TITLE
Thorswap token not showing up after update

### ISSUE THREAD

**Issue by Howedog** [asgardex/asgardex-desktop#376]
Thorswap token not showing up after I updated to new version today

## Issue description

Sent Thorswap token to Asgardex wallet today and total of tokens was shown under eth tokens. Tried to swap Thorswap token to USDT didn't work then tried the same to USDC thinking it may have been lack of USDT in wallet. they both didn't work and came up with an error I then checked to see if there was a wallet upgrade available and there was so I updated. when I opened the Asgardex wallet again there was no Thorswap token visible in the wallet but i can still find it in there on Etherscan. I then thought if I sent some more Thorswap token to the wallet it might remember to show the rest but that wasn't the case.   

Eth wallet address: 0xcf7ebDf85eA5F2B824E15F67485eBA09246eBAf1

- ASGARDEX desktop version: V1.22.4

- Operating system and version: WINDOWS

- Transaction hash(es):

Thanks

- Wallet address(es): As listed above

**Comment by GrassRootsCrypto** [comment]
Hi Howedog

If you go to the settings, wallet section, ETH chain, you can add THOR to the list of tokens that load in the Wallet/ETH section. 

By default not all tokens are loaded to save on load time however you can add or remove tokens as you wish. See https://youtu.be/g4eZ42LzfoM?t=72 for more info. 

Let us know if this doesn't work for you.
