### ISSUE TITLE
FIX: USDC swap before quote shows wrong fee decimals 

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#39]
## Expected Behavior

Estimated fees to be displayed properly for usdc before quote displayed

## Current Behavior

Estimated Fees 1,200000000 

## Steps to Reproduce

1. load app
2. Unlock
3. swap page for USDC
4. view estimated fees 

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version:

- Operating system and version:

## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by GrassRootsCrypto** [comment]
Cannot reproduce - closing for now.
