### ISSUE TITLE
Error: Expected property "1" of type biginteger, got a...

### ISSUE THREAD

**Issue by eloyesp** [asgardex/asgardex-desktop#396]
While trying to make a swap from BCH to RUNE it raises: "Error: Expected property "1" of type biginteger, got a" (the text is cut there)

View transaction and Track transaction are disabled. The only enabled button is "Finish"

## Expected Behavior

I would expect the swap to complete.

## Current Behavior

Nothing after the error.

## Steps to Reproduce

1. Import/create a wallet
2. Send BCH to the address
3. Swap to RUNE
4. FAIL

## Possible Solution

Not a clue

## Your Environment - Release Version (skip if not using a release version)

Linux

- ASGARDEX desktop version: V1.22.5.

- Operating system and version: Linux (AppImage)

**Comment by Thorian1te** [comment]
will look into this error

**Comment by eloyesp** [comment]
Hi... it seems that the issue is fixed for SWAPs, but I've found exactly the same error message when trying add "add liquidity".
