### ISSUE TITLE
Swapping RUNE and CACAO

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#398]
## Prerequisites

Have RUNE in ASGAREX

## Expected Behavior

Allow swapping to CACAO

## Current Behavior

Maya Protocol does not seem to be supported as an L1 destination.

## Steps to Reproduce

1. Have RUNE
2. Start swap
3. Attempt to find Maya chain and CACAO as destination asset

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: Asgrardex 1.22.5 (installed from deb file downloaded from GH)

- Operating system and version: Debian Testing

**Comment by Thorian1te** [comment]
I understand this is (backwards) and we are working on a fix, but did you have MAYA as the selected dex?

**Comment by erikd** [comment]
I had THOR.RUNE as the source and MAYA.CACAO as the destination. Do I need something more than that?

**Comment by Thorian1te** [comment]
<img width="537" alt="Screenshot 2024-10-10 at 12 57 03 PM" src="https://github.com/user-attachments/assets/02e9e7b8-71f4-42c2-a729-fb2ecec62d99">


I tested just now, See at the top left I have previous selected dex Maya.

**Comment by erikd** [comment]
Ok, I was doing it wrong. Will try again this afternoon. Closing this.

**Comment by erikd** [comment]
@Thorian1te Will Asgardex eventually be able to do swaps like LTC.LTC to DASH.DASH? Ie the former is not supported by Maya and the later is not supported by THORChain.

**Comment by erikd** [comment]
Yep, switching networks works.
