### ISSUE TITLE
ADD: AVAX & BSC 

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#4]
## Description

- [x] Add chain Avax
- [ ] Add chain BSC

A starting guide

•	Add icon to - src/renderer/assets/svg/ 
•	Update src/render/components/index.ts to reference the icon
•	Add chain to src/renderer/components/settings/WalletSettings.tsx L163
•	Update src/renderer/components/uielements/assets/assetIcon/AssetIcon.tsx to return the icons L4 and L105
•	Add src/renderer/components/wallet/txs/send/SendForm{Chain}.tsx for the chain screen
•	Export SendFrom Asset to src/renderer/components/wallet/txs/send/index.ts
•	Update Chain Weights in src/renderer/const.ts L134
•	Update getAddressPrefixLength in src/renderer/helpers/addressHelper.ts
•	Update src/renderer/helpers/assetHelper.ts with new assets
•	Update Re-import assets in src/renderer/helpers/chainHelper.ts with new chain
•	Add Chains to src/renderer/services/chain/address.ts for overall Service reference
•	Add Chain to src/renderer/services/chain/client.ts
•	Add Chain to src/renderer/services/chain/decimal.ts to reference the correct decimal. 
•	Update src/renderer/services/chain/transaction/common.ts for new chains
•	src/renderer/services/chain/transaction/transaction.helper.ts
•	src/renderer/services/clients/transaction/common.ts
•	Create the Service for Chain
•	Update: src/shared/utils/chain.ts
•	Add: src/shared/{chain}/client.ts
•	Update: src/renderer/views/wallet/send/SendView.tsx
•	Update:  src/renderer/views/wallet/send/SendView{Chain}.tsx
•	Update:  src/renderer/views/wallet/send/index.ts

**Comment by GrassRootsCrypto** [comment]
Issue loading balance for BSC USDC on swap and earn.

**Comment by GrassRootsCrypto** [comment]
Error withdrawing AVAX/USDC - possible dust amount issue.
