### ISSUE TITLE
Cannot Add to Savers

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#416]
Issue when adding to savers, for example ETH Savers. 

You can use the interface, and put in your password to sign the transaction but then nothing happens. 

This is because THORNode Savers Quotes broke in the last Thorndale release. 

https://discord.com/channels/838986635756044328/1290719412672004146/1290722424756768899
This should be fixed when https://gitlab.com/thorchain/thornode/-/merge_requests/3764 is released. 
Awaiting the release of https://gitlab.com/thorchain/thornode/-/milestones/146#tab-merge-requests

**Comment by GrassRootsCrypto** [comment]
![Image](https://github.com/user-attachments/assets/e3b6181a-52a4-4647-99d7-83fcbdc96c81)
now displayed

**Comment by erikd** [comment]
According to https://track.ninerealms.com/ all nodes are now running version 2.137.3, but when I try to add to the ATOM savers, the "earn" button is still disabled. Also tried with ETH (which I only have a tiny amount of) and its the same.

Opened https://github.com/asgardex/asgardex-desktop/issues/481 just to make sure this was seen.
