### ISSUE TITLE
Swap Field: Memo field removed post error state

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#419]
Using v1.22.6

Go to swap screen. Open up swap details
Force Instant Swap (don't enter any amounts)
Two fields go yellow but do not populate when I put a quote in. 
![image](https://github.com/user-attachments/assets/5f346949-c906-43e3-a62c-a958ebcaa233)
![image](https://github.com/user-attachments/assets/c8613200-1560-4c27-b5f9-19868781ef44)
Select Max so a valid quote is generated, the fields are not updated. 

Change back to a streaming swap, the swap details are not updated. 
I can work this in other ways to make the memo disappear - the details are no longer being updated after changes are made.

**Comment by Thorian1te** [comment]
<img width="592" alt="image" src="https://github.com/user-attachments/assets/aba0affc-ce5f-4d6f-8b1d-bfbbe5df181a">
im not seeing the first error

**Comment by Thorian1te** [comment]
you'll only get a memo if the quote is valid
