### ISSUE TITLE
Release 1.22.8 Feedback

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#474]
Portfolio

1. On the Portfolio page, "Total Balance of Wallet Address" should be renamed "Total Portfolio Balance" and include the sum of all values within "ALLOCATION BY TYPE" rather than just the wallet balance.
2. Add Watched Bond Address, from the Bonds tab, to the Bonds total. The watch bond feature is so bonds can be added

Bonds
1. Add a tool tip for the "Add to watch list button"
![image](https://github.com/user-attachments/assets/ded7904f-81f0-4bf0-96c9-594187876555)
2. Add a Bonds total at the top, like every other tab - it should then be the same value in the Portfolio tab

EVM
1. Cannot send ETH.Link from Ledger to Keystore. Transaction never arrives on the ledger
![image](https://github.com/user-attachments/assets/33625252-bdb0-462a-9c9c-06f764ba9e35)
2. Sending THOR - gas is in THOR but should be in ETH as gas is charged in ETH
![image](https://github.com/user-attachments/assets/b22e8f80-1ea9-4a6a-9dcc-3f1c25b1cc37)

Settings
1. White list - when opened, sort by enabled first so the enabled ones are at the top. This is good for people looking to disable tokens

**Comment by Thorian1te** [comment]
fee is fixed. .see #475

**Comment by Thorian1te** [comment]
done 
On the Portfolio page, "Total Balance of Wallet Address" should be renamed "Total Portfolio Balance" and include the sum of all values within "ALLOCATION BY TYPE" rather than just the wallet balance.
