### ISSUE TITLE
Not able to deposit ATOM into savers

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#481]
## Prerequisites

Asgardex with ATOM

## Expected Behavior

Expect deposits to savers to work

## Current Behavior

Cannot deposit because the "earn" button remains grayed out.

## Steps to Reproduce

1. Have ATOM in Asgardex
2. Go to wallets page and locate ATOM
3.  Press the "Earn" button for ATOM
4.  Enter an amount to deposit (leaving a balance of 6 ATOM)
5. "Earn" button cannot be clicked (still greyed)

Also tried with ETH and had the same issue.

Related issues https://github.com/asgardex/asgardex-desktop/issues/424 https://github.com/asgardex/asgardex-desktop/issues/416

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 1.22.8 (from GH deb file)
- Operating system and version: Debian testing

**Comment by Thorian1te** [comment]
fixing, thanks 👍

**Comment by erikd** [comment]
Can confirm this is working in 1.22.9. Thanks.
