### ISSUE TITLE
[BUG] THORChain's pools are shown in the Pools section when Maya stagenet is selected

### ISSUE THREAD

**Issue by GiMa-Maya** [asgardex/asgardex-desktop#511]
Show Maya's stagenet pools instead of THORChain's stagenet pools

**Comment by GrassRootsCrypto** [comment]
This is working correctly in develop

**Comment by GrassRootsCrypto** [comment]
@GiMa-Maya in the next release you will need to add 

REACT_APP_MIDGARD_MAYA_MAINNET_URL=https://midgard.mayachain.info
REACT_APP_MIDGARD_MAYA_STAGENET_URL=https://stagenet.midgard.mayachain.info

to your .env file.
