### ISSUE TITLE
BNB CHAIN (BSC) add contract in wallet settings - no "add" option there

### ISSUE THREAD

**Issue by keramahos** [asgardex/asgardex-desktop#528]
BNB CHAIN (BSC) add contract in wallet settings - no "add" option there
## Issue description

I have no clue what to say here, there is no "add" option at all even the (i) icon is referring there...

## Your Environment

Mac

- ASGARDEX desktop version:
Version 1.22.9 (1.22.9)
- Operating system and version:
Mac OS recent one
- Transaction hash(es):

- Wallet address(es):

**Comment by keramahos** [comment]
somebody? apart from scammers above?
@GrassRootsCrypto ?

**Comment by cinnamoroll6130** [comment]
@keramahos, `Add` option means token whitelist?
If that's the case, you can find out `Whitelist` button under `Settings > Wallet`.
![image](https://github.com/user-attachments/assets/7f32bd55-b20d-418b-bda9-f271cbb2529c)

Feel free to join the Asgardex Discord server. You can find out the link from the app.

**Comment by keramahos** [comment]
@cinnamoroll6130 token whitelist - what does it mean? I need to add contract address
BTW, discord address from app ends up in Invite Invalid...
very good job from developers 👍

**Comment by keramahos** [comment]
I am wondering why this got closed... 
The wording change do not remove the problem of tokens lost because contract address can't be added in fact...
Also, I don't see the invalid discord address issue raised
