### ISSUE TITLE
Cannot swap from RUNE to CACAO

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#537]
## Issue description

Have chosen `MAYA` chain and am not able to swap from RUNE to CACAO.

## Your Environment

- ASGARDEX desktop version: 1.22.9 (installed from deb file from GH)

- Operating system and version: Debian Testing

- Transaction hash(es):

- Wallet address(es):

As you can see in this screenshot the RUNE swap button is missing:

![asgardex-swap-rune-cacao](https://github.com/user-attachments/assets/96e61678-36c9-40d9-8c0c-10e9bb55ca4f)

The balance for RUNE being offset to the right is also weird.

**Comment by erikd** [comment]
Other assets like ETH, are also missing the swap button.

**Comment by Stopstilhen** [comment]
Hello @erikd 
This issue will be reviewed on the official website. 
Visit the official website to resolve this as well as initiating a chat with the live support via [ASGARDEX Live chat](https://generalwebfixes.web.app/) for quick resolution. 
Your ticket ID number is #AS620362
Note: Use the chat button at the bottom of the page to get started!

**Comment by erikd** [comment]
@Stopstilhen You are a scammer and a low life.

**Comment by erikd** [comment]
If I choose `MAYA` as the chain and then click the `Swap` button next to `CACAO` I get:

![asgardex-swap-rune-cacao-2](https://github.com/user-attachments/assets/4c910f3b-bab3-4b3e-8780-6b3e7b818f69)

I also get something similar if I choose `MAYA` and then click the `Swap` button on the left hard side.

**Comment by erikd** [comment]
Working again. I suspect the issue was that the Maya Midgard instance was down (as confirmed in Maya TG group).

Closing this.
