### ISSUE TITLE
Error when trying to run: "A javascript error occurred in the main process".

### ISSUE THREAD

**Issue by moninah850** [asgardex/asgardex-desktop#54]
Error when trying to run: "A javascript error occurred in the main process".

Full error description:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: The specified procedure could not be found.
\\?\C:\Users\Admin\AppData\Local\ Temp\181c36bd-3c86-4719-8356-a55c82b4d081.tmp.n...
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
at Module._extensions..node (node:internai/modules/cjs/loader-1205:18)
at Objectfunc [as .node] (node:electron/js2c/asar_bundle:5:2039)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module, load (node:internal/modules/cjs/loader:829:12)
at c.load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at load
(C:\Users\Admin\AppData\Local\Programs\asgardex\resources\app.asar\node module..:10)
at Object.<anonymous>
(C:\Users\Admin\AppData\Local\Programs\asgardex\resources\app.asar\node_module...36)

OS: Windows 7
Version Asgardex: 1.20.3

**Comment by Thorian1te** [comment]
interesting, are you able to try this with the latest version 
see release page v1.20.5
delete downloaded Version Asgardex: 1.20.3 - download version above - try installing. 
OS: Windows 7 - hmm I don't have win 7 to test with.

**Comment by GrassRootsCrypto** [comment]
@moninah850 can you please verify this with the latest release 1.20.6.
I'll close if there is no word back.

**Comment by moninah850** [comment]
> @moninah850 can you please verify this with the latest release 1.20.6. I'll close if there is no word back.

I checked version 1.20.6. The error remains.

**Comment by GrassRootsCrypto** [comment]
@moninah850 do you have a windows 10 or 11 machine you can use?
I can't see us supporting Windows 7 any time soon tbh.

**Comment by moninah850** [comment]
> @moninah850 do you have a windows 10 or 11 machine you can use? I can't see us supporting Windows 7 any time soon tbh.

No, I do not have.
