### ISSUE TITLE
Unable to add tokens that are not showing up in balances for BNB (bsc)

### ISSUE THREAD

**Issue by louiscardinal** [asgardex/asgardex-desktop#560]
Balances of tokens that would show up on elsewhere (thorswap) would not be showing in asgardex.

I was onboarding a new user to thorchain via asgardex and he proceeded to create a keystore and sent BNB and USDC via bsc. The BNB balance arrived but no USDC token ever appeared. With the current version of asgardex (1.22.9) there is a tooltip information icon that suggests adding the token in the wallet settings, however we explored all options in the GUI and there was no such feature available.

I am not sure if this issue would occur for other chains and tokens as well.

This was done on windows desktop as of 12/16/2024

- ASGARDEX desktop version: 1.22.9

- Operating system and version: Win10 x64

**Comment by louiscardinal** [comment]
Update: I checked the recent update video from Grassroots crypto and finally found the 'whitelist' button. It is so small and hidden. I recommend moving the whitelist button right beside the rectangular row of options in the center (to the left of 'export') instead of having it alone to the side so hidden.

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [LIVE SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
