### ISSUE TITLE
Ledger tx gives 403 Error

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#62]
When sending a Ledger Tx, the user is presented with a 403 error. 
Same also happens with a message deposit.

![image](https://github.com/asgardex/asgardex-desktop/assets/40199525/d329dec6-6ffa-49ac-a183-95671b9d584e)

Keystore works fine

## Reason
Keystore has implemented 9R headers, ledger has not. 

https://github.com/asgardex/asgardex-desktop/blob/develop/src/main/api/ledger/thorchain/transaction.ts#L66 sends a request to 9R 

It is believed this is the source of the error.
Looking at this code
```
 console.log('Sending data:', sdk, signer)
   let {
      data: { result: account }
    } = await auth.accountsAddressGet(sdk, signer)
    console.log('Received result:', account)
 ```
account is never returned. 

```
dev:*electron] NodeURL is: https://thornode.ninerealms.com
[dev:*electron] Got ChaidID: thorchain-mainnet-v1        
[dev:*electron] Sending data: CosmosSDK {
[dev:*electron]   url: 'https://thornode.ninerealms.com',
[dev:*electron]   chainID: 'thorchain-mainnet-v1'        
[dev:*electron] } AccAddress {
[dev:*electron]   _value: [
[dev:*electron]      70, 160, 146, 212,  89, 208,        
[dev:*electron]     214, 188,  64,  74,   0,  72,        
[dev:*electron]      49, 169, 117, 103, 189,  11,        
[dev:*electron]      24, 255
[dev:*electron]   ]
[dev:*electron] }
```
As 9R have taken protective steps against DODs, the request is not authorised. 

## Solution

Add a header to the request before it is sent.

**Comment by Thorian1te** [comment]
Can't add a header to this as `cosmos-client` doesn't export axios instance. 
package will be remove and `@cosmos-client/core` will be used instead

**Comment by GrassRootsCrypto** [comment]
Fixed
