### ISSUE TITLE
ADD THORName Management

### ISSUE THREAD

**Issue by Feedurhead-1** [asgardex/asgardex-desktop#65]
## Description

with Thorswaps new terms of service the need for an open way to buy/renew thornames has become critical, would be great to see this on Asgardex.

**Comment by GrassRootsCrypto** [comment]
> ## Description
> with Thorswaps new terms of service the need for an open way to buy/renew thornames has become critical, would be great to see this on Asgardex.

Do you mean being able to buy and update thornames in Asgardex?
Note there is https://github.com/asgardex/asgardex-desktop/issues/6 in development which will allow a user to buy and renew a thorname.

**Comment by Feedurhead-1** [comment]
Hey yes awesome.  As of now only on thorswap, would be great to see on asgardex.
thanks

**Comment by Thorian1te** [comment]
yes it is coming to asgardex in this release

**Comment by GrassRootsCrypto** [comment]
Works for new thornames and for adding a BTC address.
Can add for 1 to 5 years and cost estimate given in RUNE. 
Update example.


![Image](https://github.com/asgardex/asgardex-desktop/assets/40199525/cec4b570-bc6e-42e5-a1d3-8948b2988b5a)
