### ISSUE TITLE
Preview of the swaps/earns/loans without balances

### ISSUE THREAD

**Issue by HostFat** [asgardex/asgardex-desktop#66]
## Description

Can you make it possible to get preview of the swaps/earns/loan even without having any balances on the selected assets?

**Comment by Thorian1te** [comment]
This can be possible. 👍

**Comment by GrassRootsCrypto** [comment]
Swap is done, you can get a quote without a wallet connected.

**Comment by GrassRootsCrypto** [comment]
Closing for now. Will look to do quotes when lending is implemented.
