### ISSUE TITLE
Fix RUNE Tx sequence mismatch

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#73]
## Description
RUNE sometimes shows an error when sending txs, e.g. "account sequence mismatch, expected 30, got 29: incorrect account sequence"

See https://discord.com/channels/838986635756044328/1168595765065691259/1168706720994955274 for the fix

Will require an xchainjs fix - https://github.com/xchainjs/xchainjs-lib/issues/889

**Comment by Thorian1te** [comment]
There isn't really a fix to this, don't back to back swap within a minute.
