### ISSUE TITLE
1.20.6 Pool "LP Share" listed multiple times

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#79]
## Prerequisites

I suspect you need to have a wallet with an LP position that has been added to a couple of times.

## Expected Behavior

LP for any pool should only be listed once.

## Current Behavior

I have a couple of LPs that I have added to numerous times. Under "LP Shares" each of those are listed more than once. For the one pool I have only done one deposit into, the LP position is only listed once. For each poll that is duplicated, each line it is listed on is identical.

## Steps to Reproduce

1. Have a wallet with an LP postion that has been added to at least ones (not counting the original)/
2. Go to "LP Shares" page
3. Notice duplicate entries and that the total balance is wrong.
4.

## Your Environment - Release Version (skip if not using a release version)

1.20.6 release on Debian Linux
- ASGARDEX desktop version: 1.20.6

- Operating system and version: Debian LInux Testing

**Comment by Thorian1te** [comment]
Thank you for the feedback. This looks like it  is just a display error. We shall have it fixed in the next release.

**Comment by erikd** [comment]
Thanks!
