### ISSUE TITLE
BOND tools

### ISSUE THREAD

**Issue by Thorian1te** [asgardex/asgardex-desktop#83]
2) Bond tools needed better. When I paste in a node address to monitor, I should be able to see if I am a bond provider and bonb/unbond the amount. right now I have to go to API endpoint to get exact amount to unbond. 
RUNE/Deposit/Bond: load up node details on paste in address to review before bonding (eg who operator is and bond poviders, bond amounts etc)
RUNE/DEPOSIT/Unbond: load up node details on paste in address to see how much Bond I have to Unbond, and allow "ALL" unbond option

Related to https://github.com/asgardex/asgardex-desktop/issues/88

**Comment by GrassRootsCrypto** [comment]
From https://github.com/asgardex/asgardex-desktop/issues/88
Update node and bond management for node operators and bond providers

Add more information:
If they are the node operator, add functions to view and manage bond, total bond and see the provider list.
If they are a provider then see bond and manage bond.

Will be taken from the node address entered in the bonds section.

Add buttons to unbond or bond and then routes to the despot page (bond and unbound section)
Can only unbond if the node is in the active state.

Will use your keystore and any connected ledger address to see if you are a node operator or bond provider.
