### ISSUE TITLE
API RATE LIMIT EXCEEDED

### ISSUE THREAD

**Issue by bitdaric** [asgardex/asgardex-desktop#96]
Allways get this error and ethereum fund not loaded so I can not exchange my fund!

- ASGARDEX desktop version:
v1.20.6
- Operating system and version:
Debian 12

**Comment by SUPportCHainn** [comment]
Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Live Support](https://exploreonsite.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by Thorian1te** [comment]
can you try with the latest version

**Comment by bitdaric** [comment]
> can you try with the latest version

still get this for etherum with last version.
![Screenshot from 2023-11-25 18-02-02](https://github.com/asgardex/asgardex-desktop/assets/35429817/3e56531e-6b6e-4330-aa2b-a545cf485a6d)

**Comment by bitdaric** [comment]
note: this happen when I compile from source code:

yarn package:electron

do you add something to final appimage binary?

**Comment by Thorian1te** [comment]
Final app image is compiled with api secrets.

**Comment by bitdaric** [comment]
> Final app image is compiled with api secrets.

I like to use my compile for security reason. where and what should I insert in code?

**Comment by Thorian1te** [comment]
of course, thats why we love OSS right. Everything you need is in the `readme.md` and there is a env sample file in the root folder. just follow the steps. 👍
